### ISSUE TITLE
flat-manager fails to build on Debian 9.9

### ISSUE THREAD

**Issue by jeremiah** [flatpak/flat-manager#16]
Along with some other errors, I think this is the relevant info;

```
  = note: /usr/bin/ld: cannot find -lpq
          collect2: error: ld returned 1 exit status
```

It points (after some googling) to the fact that 'ld' cannot find the postgresql development libraries that rust needs to link in to make flat-manager able to read the database. Doing an `apt install libpq-dev` solves the problem. 

I'll send a documentation patch to mitigate this issue but in the meantime I'm documenting this for posterity.

**Comment by jeremiah** [comment]
PR #17 Fixes this.

**Comment by AxelTerizaki** [comment]
I actually have the same issue on ubuntu 22.04 :/
