### ISSUE TITLE
[flat-manager-client] Unexpected TypeError exception in publish

### ISSUE THREAD

**Issue by oleid** [flatpak/flat-manager#23]
When publishing a build, I get the following error:

```
$ flat-manager-client publish http://flatpak/api/v1/build/77
Publishing build http://flatpak/api/v1/build/77
Unexpected TypeError exception in publish: the JSON object must be str, not 'dict'
Traceback (most recent call last):
  File "flat-manager-client.1", line 680, in <module>
    "result": args.func(args),
  File "flat-manager-client.1", line 545, in publish_command
    job = publish_build(args.build_url, args.wait, args.token)
  File "flat-manager-client.1", line 374, in publish_build
    reparse_job_results(job)
  File "flat-manager-client.1", line 260, in reparse_job_results
    job["results"] = json.loads(job.get("results", "{}"))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
```

I get it all the time, since I set up the server. The publishing, however, is successful, so I ignored the error 'till today. Nevertheless, I'm wondering if I'm the only one to get the exception?

Adding a `print(job)` before the crash, I get the following:
```python
{
   'location':'http://flatpak/api/v1/build/77/publish',
   'log':'',
   'repo':'stable',
   'status':0,
   'start_after':None,
   'contents':'{"build":77}',
   'kind':1,
   'results':{},
   'id':124
}
```

So it would seem, that `"results"` is already valid json?

**Comment by nanonyme** [comment]
I think you mean that it's a dict instead of being JSON.

**Comment by razzeee** [comment]
Is that really the correct url? seems to be missing the `.org` part?

**Comment by oleid** [comment]
Oh, that's a private instance of a flat manager server.

**Comment by razzeee** [comment]
And that server is up to date? Cause it should return a string in the `results` field, as far as I can tell.

**Comment by oleid** [comment]
> And that server is up to date? Cause it should return a string in the `results` field, as far as I can tell.

Well, that bug report is 2.5 years old. Meanwhile the server has a later version. With what is currently running, I cannot reproduce it anymore. Closing the issue.
